baseURL = "https://www.pojoni.dev/"
languageCode = "en-us"
theme = "uilite"
title = "Christian Pojoni"
summary = "I am a freelance developer who is proficient in PHP, WordPress and JavaScript."
keywords = "WordPress, web development, web design, PHP, JavaScript, JS, Docker, Linux, EcmaScript, plugin, theme"
